version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["#NETWORK_PORTS#"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_CLUSTER_NAME: "#CLUSTER_NAME#"
      CONCOURSE_EXTERNAL_URL: https://#ACESS_URI#
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_TLS_CERT: #CONCOURSE_TLS_CERT#
      CONCOURSE_TLS_KEY: #CONCOURSE_TLS_KEY#
      CONCOURSE_MAIN_TEAM_CONFIG: #CONCOURSE_MAIN_TEAM_CONFIG#
      CONCOURSE_ADD_LOCAL_USER: #USER_LIST#
      CONCOURSE_MAIN_TEAM_LOCAL_USER: #TEAM_LIST#
      CONCOURSE_TLS_BIND_PORT: 443
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      # enable DNS proxy to support Docker's 127.x.x.x DNS server
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_CONTAINERD_DNS_SERVER: "#CONCOURSE_CONTAINER_DNS#"
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
